<?php

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\DependencyInjection\ServiceProviderBase;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\DependencyInjection\Definition;
use Drupal\user\Entity\User;



//working
function custom_order_event_cron() {
    	
  $current_time = \Drupal::time()->getRequestTime();
  $start_time = $current_time - (15 * 60);
  $end_time = $current_time + (15 * 60);
  $query = \Drupal::database()->select('webform_submission', 'w');
  $query->leftjoin('webform_submission_data', 'cname', 'w.sid = cname.sid');
  $query->fields('w',['sid']);
  $query->fields('cname',['value']);
  $query->condition('cname.value', 'in progress', '=');
  $query->condition('w.created', $start_time, '>=');

  //START
  $submissions_to_remove = $query->execute()->fetchCol();
 
  // Remove webform submissions.
  foreach ($submissions_to_remove as $submission_id) {
  $webform_submission_entity = \Drupal\webform\Entity\WebformSubmission::load($submission_id);
  if ($webform_submission_entity) {
  $webform_submission_entity->delete();
  }
  }
  
}